BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `TraceSample` (
	`SampleID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FlightID`	INTEGER NOT NULL,
	`Latitude`	REAL NOT NULL,
	`Longitude`	REAL NOT NULL,
	`Altitude`	REAL,
	FOREIGN KEY(`FlightID`) REFERENCES `Flight`(`FlightID`)
);
CREATE TABLE IF NOT EXISTS `Site` (
	`SiteID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SiteName`	TEXT NOT NULL DEFAULT 'Unknown site',
	`Latitude`	REAL NOT NULL,
	`Longitude`	REAL NOT NULL,
	`Altitude`	REAL NOT NULL,
	`Radius`	REAL NOT NULL DEFAULT 50
);
CREATE TABLE IF NOT EXISTS `Glider` (
	`GliderID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Brand`	TEXT,
	`Model`	TEXT,
	`EnCertification`	INTEGER
);
CREATE TABLE IF NOT EXISTS `Flight` (
	`FlightID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`TakeOffSiteID`	INTEGER NOT NULL,
	`LandingSiteID`	INTEGER NOT NULL,
	`GliderID`	INTEGER NOT NULL,
	`TakeOffDateTime`	TEXT NOT NULL,
	`FlownDistance`	REAL NOT NULL,
	`FlightDuration`	REAL NOT NULL,
	`CumulatedElevation`	REAL NOT NULL,
	`MaxAltitude`	REAL NOT NULL,
	`File`	TEXT NOT NULL,
	`FlightType`	INTEGER NOT NULL,
	`Comment`	TEXT NOT NULL,
	FOREIGN KEY(`GliderID`) REFERENCES `Glider`(`GliderID`),
	FOREIGN KEY(`LandingSiteID`) REFERENCES `Site`(`SiteID`),
	FOREIGN KEY(`TakeOffSiteID`) REFERENCES `Site`(`SiteID`)
);
COMMIT;
